from typing import TypedDict, Any


# This service will define the State, Nodes, and Graph for our LangGraph implementation


# First, we'll define the State of our Graph
# You can think of State like a container for global data. The "state" of the app.
# Each Node in the Graph can read from and write to State
# This class syntax makes GraphState a subclass of TypedDict with params
class GraphState(TypedDict, total=False): #total=False makes all fields optional
    # The most recent user query
    query: str

    # The "routing decision" we make. This tells the app what node to invoke next
    route: str

    # Any retrieved documents from the Vector DB
    docs: list[dict[str, Any]]

    # The most recent answer generated by the LLM
    answer: str

